// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet;

namespace Projet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220306183620_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projet.Models.Utilisateur", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courriel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Adresse = "adress1",
                            Courriel = "user@mail.com",
                            DateNaissance = new DateTime(2022, 3, 6, 13, 36, 20, 419, DateTimeKind.Local).AddTicks(8760),
                            MotDePasse = "eUNII0SSTvlI7K6LMD/F5aMGGEm3Fj1d89N4HOoFKAE=",
                            Nom = "user",
                            Prenom = "user",
                            Role = "User",
                            Telephone = "111"
                        },
                        new
                        {
                            Id = 2L,
                            Adresse = "adress2",
                            Courriel = "admin@mail.com",
                            DateNaissance = new DateTime(2022, 3, 6, 13, 36, 20, 424, DateTimeKind.Local).AddTicks(6875),
                            MotDePasse = "OHVv+u4mWEQqeCR0MfD8jlPCST6M8f0AYab+lDy+TRI=",
                            Nom = "admin",
                            Prenom = "admin",
                            Role = "Admin",
                            Telephone = "222"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
