// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet;

namespace Projet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220306023146_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projet.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            UserAdress = "adress1",
                            UserDateOfBirth = new DateTime(2022, 3, 5, 21, 31, 46, 613, DateTimeKind.Local).AddTicks(4610),
                            UserEmail = "user@mail.com",
                            UserFirstName = "user",
                            UserName = "user",
                            UserPassword = "eUNII0SSTvlI7K6LMD/F5aMGGEm3Fj1d89N4HOoFKAE=",
                            UserRole = "User"
                        },
                        new
                        {
                            UserId = 2L,
                            UserAdress = "adress2",
                            UserDateOfBirth = new DateTime(2022, 3, 5, 21, 31, 46, 618, DateTimeKind.Local).AddTicks(3022),
                            UserEmail = "admin@mail.com",
                            UserFirstName = "admin",
                            UserName = "admin",
                            UserPassword = "OHVv+u4mWEQqeCR0MfD8jlPCST6M8f0AYab+lDy+TRI=",
                            UserRole = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
